### ISSUE TITLE
Could you make the endpoint for getting cases by date?

### ISSUE THREAD

**Issue by pratamov** [FerdinaKusumah/corona-api#1]
hi man, nice API, good job

If it possible could you add an endpoint as this spec?

```
GET <HOST>/get_by_date?date=yyyy-MM-dd
```
to retrieving cases by date

**Comment by pratamov** [comment]
you can use [this dataset](https://covid.ourworldindata.org/data/ecdc/full_data.csv)

source: https://ourworldindata.org/coronavirus-source-data

**Comment by FerdinaKusumah** [comment]
Yes, maybe we can used the data if that source is trusted.
Offcourse you can make an PR for this feature

**Comment by FerdinaKusumah** [comment]
Hi @pratamov, thankyou for interesting with this repo. I'm already update repo with historical data from ur datasource.
Please check this documentation for detail 
`https://corona-live-api.herokuapp.com/docs#/default/history_data_history_get`
